### ISSUE TITLE
ZeligEI: summary not working for ecological inference RxC models

### ISSUE THREAD

**Issue by michalskop** [IQSS/Zelig#151]
I'm getting this error:

```
> summary(z.out)
Model: 
Error in summary.eiMD(.$z.out) : could not find function "is.mcmc"
```

I am able to get some of the results by:
`mat = matrix(apply(as.matrix(z.out$getcoef()[[1]][[3]]),2,'mean'),ncol=3)`
and
`matsd = matrix(apply(as.matrix(z.out$getcoef()[[1]][[3]]),2,'sd'),ncol=3)`
(where ncol=3 needs to be adjusted to the respective case)

My full code with columns named `A1 ... An` and `B1 ... Bm` in a dataset in `par_input`

```
library("Zelig")
library("ZeligEI")
data <- read.csv(par_input, header = TRUE, fileEncoding = "utf-8", encoding = "utf-8")
variables <- names(data)
As <- variables[which(grepl("A", variables) == TRUE)]
Bs <- variables[which(grepl("B", variables) == TRUE)]
z.out = zeirxc$new()
eval(parse(text = paste0( "z.out$zelig(cbind(" , paste(Bs, collapse = ", "), ") ~ cbind(", paste(As, collapse = ", "), "), N='ZeligN', data = data)")))
summary(z.out)
```

**Comment by tercer** [comment]
This seems to be a namespace issue.  A workaround is to attach "eiPack" directly so the right function can be found.  Will fix this shortly, but for the present, add:
    library("eiPack")
and summary works.

**Comment by tercer** [comment]
This is now solved on the Beta on GitHub, and will be pushed to CRAN with version 0.1-1

The issue was for safer namespaces, adding packages through imports is generally preferred to depends.  However, eiPack has it's dependencies as strict Depends so expects required functions to be attached, so eiPack thus has to be a "Depends" rather than an "Imports" so eiPacks own dependencies are attached correctly.
