### ISSUE TITLE
sim() in 5.0-13 fails if model includes factor variables

### ISSUE THREAD

**Issue by altaf-ali** [IQSS/Zelig#156]
In version 5.0-13 of Zelig, `sim()` function fails with the following error if the model includes a factor variable:

```
Error in simparam$simparam %*% t(mm) : non-conformable arguments
```

The same code works fine in previous version 5.0-12.

`Species` is a factor variable in the following example. If you remove it or replace it with a continuous variable, then `sim()` works fine.

#### code to reproduce the error:

```R
library(Zelig)

z.out <- zelig(Petal.Width ~ Petal.Length + Species, data = iris, model = "ls")
x.out <- setx(z.out, Petal.Length = 1:10)
s.out <- sim(z.out, x.out)

## Error in simparam$simparam %*% t(mm) : non-conformable arguments
```

**Comment by christophergandrud** [comment]
It looks like the issue may have to do with the model matrix `mm` being malformed on line: https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L589

**Comment by christophergandrud** [comment]
Some more details: when the `mm` is created it is of length 3 with one value set at the fitted factor variable level (in this case `3`) rather than a `0` then `1` to match the 4 parameters in `simparam$simparam`.

**Comment by christophergandrud** [comment]
More narrowing: bug was introduced in 76b47c4a88f11d75015dc3f3e5d49a1a3a356045

**Comment by christophergandrud** [comment]
This commit may also be related to the documentation problem: http://docs.zeligproject.org/en/latest/zelig-ls.html

Also discussed in https://groups.google.com/forum/#!topic/zelig-statistical-software/1ohCNA5S_0A

**Comment by christophergandrud** [comment]
Narrowed it down further to the `avg` function that allows users to specify which central tendancy to find: https://github.com/IQSS/Zelig/blob/master/R/model-zelig.R#L422-L429

**Comment by christophergandrud** [comment]
I solve it in 2758adf75ce41bcb71abd28ba42a86b15c9e7d75

The problem in line 428 of model-zelig (where `avg` decides what to do with factor variables) is that the old code `ifelse(is.null(fn$other), Mode(val), fn$other(val))` returned a numeric value of the modal factor level rather than the label which is needed to find the parameter in `sim`.

The fix was to just hard code `Mode(val)` so that the mode is always found for non-numeric, non-ordered variables. 

Is there a use case that I'm missing where someone would want to find another central tendency for such variables?
