### ISSUE TITLE
Survey weights in logistic regression

### ISSUE THREAD

**Issue by emazzola** [IQSS/Zelig#319]
Hello everybody,
and thanks in advance for all the information you will provide me with.

I have a couple of questions about weighted logistic regression in Zelig. Namely:
1. how the survey weights are used in the weighted logistic regression formula, and

2. I understand not everybody would know this, but I try anyway: how this use of the weights in Zelig compares with the use of the weights for logistic regression in SUDAAN ( [https://www.rti.org/impact/sudaan-statistical-software-analyzing-correlated-data] ) ? 
I have never used this software, and it's not installed anywhere in my department, but I got this request myself too from an external PI. Do you happen to know whether or not it's the same use?

Thank you very much, all the help you will give me is very appreciated!
Best,
Emanuele

**Comment by christophergandrud** [comment]
Hi @emazzola 

Quick initial responses:

1. Take a look at the logistic regression with survey weighting docs at: http://docs.zeligproject.org/articles/zelig_logitsurvey.html (I'll also do a deeper look if these aren't very helpful for you). 

FYI we recommend using `surveyglm` to fit the model then placing the resulting fitted model object into `setx` to set your fitted values rather than using `zelig` directly. `zelig` just calls `surveyglm`, which is more full featured. I would read up on the docs for `surveyglm` for the full details.

2. I've never used SUDAAN before (or have any way to access it on my computer).
